name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Utiliser le shell Bash
    defaults:
      run:
        shell: bash

    steps:
      # Étape 1 : Checkout du code source
      - name: Checkout
        uses: actions/checkout@v4

      # Étape 2 : Lister les fichiers pour le débogage (optionnel)
      - name: List Files for Debugging
        run: ls -R terraform-2406/8.aws-ec2

      # Étape 3 : Configuration de Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Étape 4 : Initialiser Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform-2406/8.aws-ec2

      # Étape 5 : Vérifier le format des fichiers Terraform
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: terraform-2406/8.aws-ec2

      # Étape 6 : Générer le plan Terraform
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: terraform-2406/8.aws-ec2

      # Étape 7 : Appliquer les changements Terraform (uniquement sur push vers main)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: terraform-2406/8.aws-ec2
